apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - app.bytecraft.local
  #     secretName: bytecraft-tls
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: bytecraft-service
            port: 
              number: 8080
